### ISSUE TITLE
Code splitting loads one vendor module twice 

### ISSUE THREAD

**Issue by dylanjha** [crowdcst/webpack-test#1]
In current master https://github.com/crowdcst/webpack-sandbox/tree/602cd446befd05eb40b8f4f10ad7b3257f201a5f

There is one vendor module: `js/vendor-1.js`. This is loaded inside a code-splitting statement (`require.ensure`) in two different app modules:

* `app-2.js` (by itself)
* `app-3.js` (alongside another vendor module (`vendor-2.js`)

The result is that two chunks are created:

* 0.js (contains vendor-1 AND vendor-2)
* 1.js (contains vendor-1)

As a result, the contents of vendor-1 exists in both automatically split chunks. When the index page loads the content of vendor-1 gets sent over the wire twice.

![image 2017-03-16 at 11 11 48 pm](https://cloud.githubusercontent.com/assets/764988/24031132/23252aba-0a9e-11e7-889d-c161518d1ad9.png)
![image 2017-03-16 at 11 11 24 pm](https://cloud.githubusercontent.com/assets/764988/24031134/256a762c-0a9e-11e7-9a5c-e753b175b63f.png)

**Comment by TheLarkInn** [comment]
`new webpack.CommonsChunkPlugin({children: true, async: true, filename: "async-commons.js"})` might do the trick for this :-D

**Comment by dylanjha** [comment]
got it, now that generates an `async-commons.js` file, but that doesn't "just work". It appears that webpack does not know that it has to load this file, what's the next step?

If you want to see what I mean checkout the branch https://github.com/crowdcst/webpack-sandbox/tree/async-commons and you'll see what I mean.

-------------


<img width="734" alt="image 2017-04-14 at 9 21 59 pm" src="https://cloud.githubusercontent.com/assets/764988/25060698/7faac2d8-2158-11e7-9d80-9eb038508da0.png">

**Comment by dylanjha** [comment]
Webpack docs say:

https://webpack.github.io/docs/list-of-plugins.html#4-extra-async-commons-chunk

> This is automatically downloaded in parallel when the additional chunk is downloaded.

But for some reason, my `async-commons` chunk is not being automatically downloaded in parallel

**Comment by dylanjha** [comment]
removing the `{filename: 'async-commons'}` works now, and the default chunk name of 0.js or 1.js works now and gets automatically downloaded
